security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Resanet\UtilisateurBundle\Entity\Utilisateur:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    providers:
        chain_provider:
            providers: [in_memory, main]
        main:
            entity: { class: ResanetUtilisateurBundle:Utilisateur, property: identifiant }
        in_memory:
            users:
                admin:  { password: admin, roles: 'ROLE_SUPER_ADMIN' }    
              
    
    firewalls:
        secured_area:
            logout:
                path:   /deconnexion
                target: /connexion
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /connexion
                check_path:  /verification

    access_control:
        - { path: ^/admin/parametres, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
        
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
