parameters:
#    resanet_site.example.class: Resanet\SiteBundle\Example

services:
#    resanet_site.example:
#        class: %resanet_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
