parameters:
#    resanet_stat.example.class: Resanet\StatBundle\Example

services:
#    resanet_stat.example:
#        class: %resanet_stat.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
