parameters:
#    resanet_main.example.class: Resanet\MainBundle\Example

services:
#    resanet_main.example:
#        class: %resanet_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
