parameters:
#    resanet_paiement.example.class: Resanet\PaiementBundle\Example

services:
#    resanet_paiement.example:
#        class: %resanet_paiement.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
