parameters:
#    resanet_utilisateur.example.class: Resanet\UtilisateurBundle\Example

services:
#    resanet_utilisateur.example:
#        class: %resanet_utilisateur.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
